name = "My NeoForge Pack"
author = "yungspiderq"
version = "1.3.1"
description = "Приватный модпак с автосинхронизацией через GitHub Pages"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a42a443ffb044e74726e558f90e7e4c648e956ea159270d9a0eff6189e6cd4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
