name = "My NeoForge Pack"
author = "yungspiderq"
version = "1.2.0"
description = "Приватный модпак с автосинхронизацией через GitHub Pages"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b87f64f8ecfc5ecc653cad30a9668106fa9814e49e19fa18328a669aca1eedc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
