# -*- coding: utf-8 -*-
"""
Глава 5 — «Вечное Звездосветье» (мод Eternal Starlight 0.9.1+1.21.1+neoforge).

Глава-витрина контентного мода, построена генератором с проверкой покрытия:
union всех item-задач главы равен полному списку item-форм мода из jar
(1195 моделей минус spawn-egg) — ни один предмет, клинок, сет брони, пластинка
или строительный блок не потерян. Длинные чек-листы разбиты на тома по 15 задач
(ограничение схемы ID пака): том продолжает предыдущий цепочкой deps.
Секции: дорога и картография, бестиарий с обоими боссами, руды и материалы,
девять тиров снаряжения и уникальное оружие, кухня и диковины, строительные
наборы и финальная «Звёздная энциклопедия».
"""

from qdsl import (CUSTOM, Q, SEC, biome, dim, give, item, kill, lvl, struct,
                  toast, xpr)

CLR_ROAD = 0x2B4C7E
CLR_BESTIARY = 0x6A4C93
CLR_ORES = 0x1F7A70
CLR_ARSENAL = 0x8C5A2B
CLR_TABLE = 0x7A1F4C
CLR_BUILDING = 0x556B2F
CLR_ENCYC = 0xC9A227

SECTIONS = [
    SEC("road", ('The Road to the Starlight', 'Дорога в Звездосветье'), CLR_ROAD),
    SEC("bestiary", ('The Bestiary', 'Бестиарий'), CLR_BESTIARY),
    SEC("ores", ('Ores and Materials', 'Руды и материалы'), CLR_ORES),
    SEC("arsenal", ('The Arsenal', 'Арсенал'), CLR_ARSENAL),
    SEC("table", ('Table and Pocket', 'Стол и карман'), CLR_TABLE),
    SEC("building", ('Building', 'Строительство'), CLR_BUILDING),
    SEC("encyc", ('The Star Encyclopaedia', 'Звёздная энциклопедия'), CLR_ENCYC),
]

QUESTS = [
# --- секция road ---
Q("q01", ('A Sky of a Million Stars', 'Небо миллиона звёзд'), section="road",
  icon="eternal_starlight:orb_of_prophecy",
  size=1.5,
  desc=[
      ('Eternal Starlight opens the Eternal Starlight dimension: night, auroras and 24 biomes.',
       'Eternal Starlight открывает измерение Вечного Звездосветья: ночь, сияния и 24 биома.'),
      ('The portal is not built from blocks - it is opened by the orb of prophecy. Get it and step through the stars.',
       'Портал не строят из блоков — его открывает сфера пророчества (orb of prophecy). Добудь её и шагни сквозь звёзды.'),
  ],
  tasks=[
      item("eternal_starlight:orb_of_prophecy"),
      dim("eternal_starlight:starlight"),
  ],
  rewards=[
      lvl(4),
      toast('Ты в Вечном Звездосветье. Небо здесь не кончается.'),
  ]),

Q("q02", ('Ruins of the Gates', 'Руины врат'), section="road",
  icon="eternal_starlight:dusted_shard",
  desc=[
      ('Others were here before you: portal ruins are scattered across the Starlight, from snows to jungles.',
       'До тебя здесь были другие: руины порталов разбросаны по всему Звездосветью — от снегов до джунглей.'),
      ('Inside - chests with dusted shards and hints of those who never returned.',
       'Внутри — сундуки с запылёнными осколками и подсказки о тех, кто не вернулся.'),
  ],
  tasks=[
      struct("eternal_starlight:portal_ruins_common"),
      struct("eternal_starlight:portal_ruins_cold"),
      struct("eternal_starlight:portal_ruins_desert"),
      struct("eternal_starlight:portal_ruins_forest"),
      struct("eternal_starlight:portal_ruins_jungle"),
  ],
  rewards=[
      xpr(160),
      give("eternal_starlight:dusted_shard", 8),
  ]),

Q("q03", ('Cartographer of Light I', 'Картограф света I'), section="road",
  icon="eternal_starlight:starlit_lily_pad",
  desc=[
      ('The first twelve biomes: from starlight forest to icy sea.',
       'Двенадцать первых биомов: от звездосветного леса до ледяного моря.'),
      ('A compass is useless here - navigate by the glow.',
       'Компас бесполезен — ориентируйся по сиянию.'),
  ],
  tasks=[
      biome("eternal_starlight:starlight_forest"),
      biome("eternal_starlight:starlight_dense_forest"),
      biome("eternal_starlight:umbral_plains"),
      biome("eternal_starlight:glimmer_scrubland"),
      biome("eternal_starlight:starlight_permafrost_forest"),
      biome("eternal_starlight:permafrost_peaks"),
      biome("eternal_starlight:starlight_taiga"),
      biome("eternal_starlight:dark_swamp"),
      biome("eternal_starlight:scarlet_forest"),
      biome("eternal_starlight:torreya_forest"),
      biome("eternal_starlight:crystallized_desert"),
      biome("eternal_starlight:lucent_mycelium_isle"),
  ],
  rewards=[
      xpr(200),
  ]),

Q("q04", ('Cartographer of Light II', 'Картограф света II'), section="road",
  icon="eternal_starlight:starlit_lily_pad",
  desc=[
      ('The remaining biomes, including the Abyss: nothing in the Starlight is darker.',
       'Остальные биомы, включая Бездну: темнее места в Звездосветье нет.'),
      ('Something lives in the Abyss that makes this chapter worth finishing.',
       'В Бездне живёт то, из-за чего главу стоило пройти до конца.'),
  ],
  tasks=[
      biome("eternal_starlight:solaris_isles"),
      biome("eternal_starlight:starlit_sky"),
      biome("eternal_starlight:shimmer_river"),
      biome("eternal_starlight:ether_river"),
      biome("eternal_starlight:starlit_sea"),
      biome("eternal_starlight:icy_sea"),
      biome("eternal_starlight:spiral_kelp_forest"),
      biome("eternal_starlight:lush_shallow_sea"),
      biome("eternal_starlight:the_abyss"),
      biome("eternal_starlight:warm_shore"),
      biome("eternal_starlight:grim_shore"),
  ],
  rewards=[
      xpr(240),
      give("eternal_starlight:starlit_painting"),
  ]),

Q("q05", ('Forge of the Legion', 'Кузница легиона'), section="road",
  icon="eternal_starlight:golem_steel_ingot",
  desc=[
      ('Three major structures: the golem forge (where starlight golems are born), the cursed garden and the stranghoul den.',
       'Три большие структуры: кузница големов (там рождаются звездосветные големы), проклятый сад и логово странгуля.'),
      ('In the forge look for energy blocks: deactivate them and the golem becomes vulnerable.',
       'В кузнице ищи энергоблоки: выключи их — и голем станет уязвим.'),
  ],
  tasks=[
      struct("eternal_starlight:golem_forge"),
      struct("eternal_starlight:cursed_garden"),
      struct("eternal_starlight:stranghoul_den"),
  ],
  rewards=[
      xpr(180),
  ]),

Q("q06", ('The Flotilla', 'Флотилия'), section="road",
  icon="eternal_starlight:lunar_boat",
  desc=[
      ('The seas of the Starlight only look calm. Seven woods - seven boats and chest boats.',
       'Моря Звездосветья спокойны только на вид. Семь пород дерева — семь лодок и грузовых лодок.'),
      ('The starlit sea is faster to cross than to walk around.',
       'Звёздное море быстрее переплыть, чем обойти по берегу.'),
  ],
  tasks=[
      item("eternal_starlight:lunar_boat"),
      item("eternal_starlight:northland_boat"),
      item("eternal_starlight:banyin_boat"),
      item("eternal_starlight:scarlet_boat"),
      item("eternal_starlight:torreya_boat"),
      item("eternal_starlight:lunar_chest_boat"),
      item("eternal_starlight:northland_chest_boat"),
      item("eternal_starlight:banyin_chest_boat"),
      item("eternal_starlight:scarlet_chest_boat"),
      item("eternal_starlight:torreya_chest_boat"),
      item("eternal_starlight:jinglestem_raft"),
      item("eternal_starlight:jinglestem_chest_raft"),
      item("eternal_starlight:cradlewood_boat"),
      item("eternal_starlight:cradlewood_chest_boat"),
  ],
  rewards=[
      xpr(90),
  ]),

# --- секция bestiary ---
Q("q07", ('Local Fauna', 'Местная фауна'), section="bestiary",
  deps=['q06'],
  icon="eternal_starlight:gleech_egg",
  desc=[
      ('Ten creatures without which the Starlight would be just an empty night.',
       'Десять существ, без которых Звездосветье было бы просто пустой ночью.'),
      ('The crystallized moth can be tamed with meat: it strikes with a sound wave.',
       'Кристального мотылька можно приручить мясом: он бьёт звуковой волной.'),
  ],
  tasks=[
      kill("eternal_starlight:ratlin", 1),
      kill("eternal_starlight:gleech", 1),
      kill("eternal_starlight:shadow_snail", 1),
      kill("eternal_starlight:aurora_deer", 1),
      kill("eternal_starlight:luminofish", 1),
      kill("eternal_starlight:rookfish", 1),
      kill("eternal_starlight:shimmer_lacewing", 1),
      kill("eternal_starlight:starfire_bird", 1),
      kill("eternal_starlight:crystallized_moth", 1),
      kill("eternal_starlight:ent", 1),
  ],
  rewards=[
      xpr(150),
  ]),

Q("q08", ('Dangerous Neighbours', 'Опасные соседи'), section="bestiary",
  icon="eternal_starlight:tentacle_spike",
  desc=[
      ('Creteors fall from the sky during meteor showers, the permafrost spits from afar, the stranghoul hunts at night.',
       'Метеориперы падают с неба в метеоритный дождь, мерзлотник плюётся издалека, странгуль охотится ночью.'),
      ('The stranghoul, by the way, can be hired with a bowl of spicy stew - for one day.',
       'Странгуля, кстати, можно нанять миской острого рагу — на один день.'),
  ],
  tasks=[
      kill("eternal_starlight:nightfall_spider", 1),
      kill("eternal_starlight:lonestar_skeleton", 1),
      kill("eternal_starlight:thirst_walker", 1),
      kill("eternal_starlight:seeker", 1),
      kill("eternal_starlight:creteor", 1),
      kill("eternal_starlight:yeti", 1),
      kill("eternal_starlight:permafrost", 1),
      kill("eternal_starlight:stranghoul", 1),
  ],
  rewards=[
      xpr(200),
      give("eternal_starlight:seeker_tentacle", 4),
  ]),

Q("q09", ('A Tangled Death', 'Запутанная смерть'), section="bestiary",
  icon="eternal_starlight:tenacious_vine",
  desc=[
      ('The tangled, its husk and skull: the tenacious vine does not let go even of the dead.',
       'Запутанный, его кадавр и череп: цепкая лоза не отпускает даже мёртвых.'),
      ('The skull explodes - you can chain it (and get the mod achievement).',
       'Череп взрывается — можно устроить цепную реакцию (и достижение пака модов).'),
  ],
  tasks=[
      kill("eternal_starlight:tangled", 1),
      kill("eternal_starlight:tangled_husk", 1),
      kill("eternal_starlight:tangled_skull", 1),
  ],
  rewards=[
      xpr(140),
  ]),

Q("q10", ('The Gatekeeper', 'Привратник'), section="bestiary",
  icon="eternal_starlight:starfire",
  size=1.6,
  desc=[
      ('First boss: the Gatekeeper tests the worthy. He hurls fireballs and tolerates no weakling.',
       'Первый босс: Привратник проверяет достойных. Он швыряет огненные шары и не терпит слабых.'),
      ('Pass his challenge - and take what he guards.',
       'Пройди его испытание — и забери то, что он стережёт.'),
  ],
  tasks=[
      kill("eternal_starlight:the_gatekeeper", 1),
  ],
  rewards=[
      lvl(10),
      toast('Привратник пал. Врата открыты.'),
  ]),

Q("q11", ('The Lunar Monstrosity', 'Лунное чудовище'), section="bestiary",
  icon="eternal_starlight:orb_of_prophecy",
  size=1.6,
  desc=[
      ('The second boss waits in the Abyss. Ignite it - only fire makes it vulnerable.',
       'Второй босс ждёт в Бездне. Подожги его — только огонь делает его уязвимым.'),
      ('Breath and thorns fly in arcs: keep your distance and do not stand in the pools.',
       'Дыхание и шипы летят по дуге: держи дистанцию и не стой в лужах.'),
  ],
  tasks=[
      biome("eternal_starlight:the_abyss"),
      kill("eternal_starlight:lunar_monstrosity", 1),
  ],
  rewards=[
      lvl(12),
      toast('Лунное чудовище одолено. Через терни — к звёздам.'),
  ]),

Q("q12", ('Wardens of Stone and Steel', 'Стражи камня и стали'), section="bestiary",
  icon="eternal_starlight:golem_steel_ingot",
  desc=[
      ('Four golems: grimstone (summoned with a carved cactus), starlight, astral and aethersent.',
       'Четыре голема: мракокаменный (призывается вырезанной опунцией), звездосветный, астральный и эфиросцентный.'),
      ('Deactivate or freeze the starlight one first - otherwise its armour shrugs off damage.',
       'Звездосветного сначала обесточь или заморозь трубкой — иначе броня держит урон.'),
  ],
  tasks=[
      kill("eternal_starlight:grimstone_golem", 1),
      kill("eternal_starlight:starlight_golem", 1),
      kill("eternal_starlight:astral_golem", 1),
      kill("eternal_starlight:aethersent_golem", 1),
  ],
  rewards=[
      xpr(220),
  ]),

# --- секция ores ---
Q("q13", ('First Tears', 'Первые слёзы'), section="ores",
  deps=['q12'],
  icon="eternal_starlight:starlit_diamond",
  desc=[
      ('Twelve materials every Starlight kit begins with.',
       'Двенадцать материалов, с которых начинается всё снаряжение Звездосветья.'),
      ('Starfire is not mined: help the starfire birds nest - and they will share.',
       'Звездопал добывают не киркой: помоги птицам-звездопалам свить гнездо — и они поделятся.'),
  ],
  tasks=[
      item("eternal_starlight:glacite_shard"),
      item("eternal_starlight:thioquartz_shard"),
      item("eternal_starlight:dusted_shard"),
      item("eternal_starlight:malarite"),
      item("eternal_starlight:starlit_diamond"),
      item("eternal_starlight:starfire"),
      item("eternal_starlight:saltpeter_powder"),
      item("eternal_starlight:shivering_gel"),
      item("eternal_starlight:soul_dew"),
      item("eternal_starlight:crinoa_ball"),
      item("eternal_starlight:lunaris_cactus_gel"),
      item("eternal_starlight:velvetumoss_ball"),
  ],
  rewards=[
      xpr(120),
  ]),

Q("q14", ('Ingots and Alloys', 'Слитки и сплавы'), section="ores",
  icon="eternal_starlight:golem_steel_ingot",
  desc=[
      ('Glacite, deepsilver, unrealium, aethersent, golem steel and flowglaze (starfire thrown into sand).',
       'Леднит, глубинное серебро, нереалий, эфиросцент, големосталь и глазутёк (звездопал, брошенный в песок).'),
      ('The alloy furnace smelts what a normal one cannot; the crystalborn catalyst runs on crystals.',
       'Доменная печь переплавляет то, что обычная не берёт; кристаллический катализатор работает на кристаллах.'),
  ],
  tasks=[
      item("eternal_starlight:deepsilver_ingot"),
      item("eternal_starlight:unrealium_ingot"),
      item("eternal_starlight:aethersent_ingot"),
      item("eternal_starlight:golem_steel_ingot"),
      item("eternal_starlight:flowglaze"),
      item("eternal_starlight:raw_amaramber"),
      item("eternal_starlight:starcore"),
      item("eternal_starlight:crystalborn_catalyst"),
      item("eternal_starlight:alloy_furnace"),
  ],
  rewards=[
      xpr(160),
  ]),

# --- секция arsenal ---
Q("q15p1", ('Springstone and Glacite · I', 'Истокамень и леднит · I'), section="arsenal",
  deps=['q14'],
  icon="eternal_starlight:thermal_springstone_sword",
  desc=[
      ('The first two tiers: thermal springstone (careful: giant plants burn only with fire) and glacite.',
       'Первые два тира: термальный истокамень (осторожно: гигантские растения сжигаются только огнём) и леднит.'),
      ('Scythes mow grass in bundles, the glacite shield holds the blow.',
       'Косы косят траву пачками, щит из леднита держит удар.'),
  ],
  tasks=[
      item("eternal_starlight:thermal_springstone_sword"),
      item("eternal_starlight:thermal_springstone_pickaxe"),
      item("eternal_starlight:thermal_springstone_axe"),
      item("eternal_starlight:thermal_springstone_scythe"),
      item("eternal_starlight:thermal_springstone_helmet"),
      item("eternal_starlight:thermal_springstone_chestplate"),
      item("eternal_starlight:thermal_springstone_leggings"),
      item("eternal_starlight:thermal_springstone_boots"),
      item("eternal_starlight:glacite_sword"),
      item("eternal_starlight:glacite_pickaxe"),
      item("eternal_starlight:glacite_axe"),
      item("eternal_starlight:glacite_scythe"),
      item("eternal_starlight:glacite_helmet"),
      item("eternal_starlight:glacite_chestplate"),
      item("eternal_starlight:glacite_leggings"),
  ],
  rewards=[
  ]),

Q("q15p2", ('Springstone and Glacite · II', 'Истокамень и леднит · II'), section="arsenal",
  deps=['q15p1'],
  icon="eternal_starlight:thermal_springstone_sword",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:glacite_boots"),
      item("eternal_starlight:glacite_shield"),
  ],
  rewards=[
      xpr(140),
  ]),

Q("q16", ('Malarite and Deepsilver', 'Маларит и глубинное серебро'), section="arsenal",
  icon="eternal_starlight:malarite_spear",
  desc=[
      ('The malarite spear outreaches a sword, sickles cut ears, the deepsilver brush is for archaeologists.',
       'Маларитовое копьё бьёт дальше меча, серпы срезают колосья, кисть глубинного серебра нужна археологу.'),
      ('Silver does not tarnish in the dusk - check what glitters in your hand.',
       'Серебро не тускнеет в сумерках — проверяй блестящее в руке.'),
  ],
  tasks=[
      item("eternal_starlight:malarite_sword"),
      item("eternal_starlight:malarite_pickaxe"),
      item("eternal_starlight:malarite_axe"),
      item("eternal_starlight:malarite_spear"),
      item("eternal_starlight:malarite_sickle"),
      item("eternal_starlight:deepsilver_sword"),
      item("eternal_starlight:deepsilver_pickaxe"),
      item("eternal_starlight:deepsilver_axe"),
      item("eternal_starlight:deepsilver_helmet"),
      item("eternal_starlight:deepsilver_chestplate"),
      item("eternal_starlight:deepsilver_leggings"),
      item("eternal_starlight:deepsilver_boots"),
      item("eternal_starlight:deepsilver_sickle"),
      item("eternal_starlight:deepsilver_brush"),
  ],
  rewards=[
      xpr(160),
  ]),

Q("q17p1", ('Starlit Diamond and Unrealium · I', 'Звёздный алмаз и нереалий · I'), section="arsenal",
  icon="eternal_starlight:starlit_diamond_sword",
  desc=[
      ('Starlit diamond is harder than diamond; unrealium is lighter than shadow and hits harder.',
       'Звёздный алмаз твёрже алмаза; нереалий легче тени и бьёт больнее.'),
      ('A full unrealium set is the mod achievement "Step into the unknown".',
       'Полный нереалиевый комплект — достижение мода «Шаг в неизведанное».'),
  ],
  tasks=[
      item("eternal_starlight:starlit_diamond_sword"),
      item("eternal_starlight:starlit_diamond_pickaxe"),
      item("eternal_starlight:starlit_diamond_axe"),
      item("eternal_starlight:starlit_diamond_helmet"),
      item("eternal_starlight:starlit_diamond_chestplate"),
      item("eternal_starlight:starlit_diamond_leggings"),
      item("eternal_starlight:starlit_diamond_boots"),
      item("eternal_starlight:unrealium_sword"),
      item("eternal_starlight:unrealium_pickaxe"),
      item("eternal_starlight:unrealium_axe"),
      item("eternal_starlight:unrealium_helmet"),
      item("eternal_starlight:unrealium_chestplate"),
      item("eternal_starlight:unrealium_leggings"),
      item("eternal_starlight:unrealium_boots"),
      item("eternal_starlight:unrealium_crossbow"),
  ],
  rewards=[
  ]),

Q("q17p2", ('Starlit Diamond and Unrealium · II', 'Звёздный алмаз и нереалий · II'), section="arsenal",
  deps=['q17p1'],
  icon="eternal_starlight:starlit_diamond_sword",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:unrealium_sickle"),
  ],
  rewards=[
      xpr(180),
  ]),

Q("q18p1", ('Starfire and Flowglaze · I', 'Звездопал и глазутёк · I'), section="arsenal",
  icon="eternal_starlight:starfire_sword",
  desc=[
      ('The crafting peak: starfire and flowglaze gear plus smithing upgrade templates.',
       'Вершина крафта: звездопальное и глазутёковое снаряжение плюс кузнечные шаблоны улучшений.'),
      ('Amaramber is got by hewing torreya logs: its chestplate glows from within.',
       'Амарянтарь добывают, обтёсывая тисовые брёвна: нагрудник из него светится изнутри.'),
  ],
  tasks=[
      item("eternal_starlight:starfire_sword"),
      item("eternal_starlight:starfire_pickaxe"),
      item("eternal_starlight:starfire_axe"),
      item("eternal_starlight:starfire_scythe"),
      item("eternal_starlight:starfire_crossbow"),
      item("eternal_starlight:starfire_upgrade_smithing_template"),
      item("eternal_starlight:flowglaze_sword"),
      item("eternal_starlight:flowglaze_pickaxe"),
      item("eternal_starlight:flowglaze_axe"),
      item("eternal_starlight:flowglaze_scythe"),
      item("eternal_starlight:flowglaze_bow"),
      item("eternal_starlight:flowglaze_shield"),
      item("eternal_starlight:flowglaze_upgrade_smithing_template"),
      item("eternal_starlight:amaramber_sword"),
      item("eternal_starlight:amaramber_chestplate"),
  ],
  rewards=[
  ]),

Q("q18p2", ('Starfire and Flowglaze · II', 'Звездопал и глазутёк · II'), section="arsenal",
  deps=['q18p1'],
  icon="eternal_starlight:starfire_sword",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:amaramber_arrow", 8),
  ],
  rewards=[
      xpr(220),
  ]),

Q("q19p1", ('Unique Arms · I', 'Уникальное оружие · I'), section="arsenal",
  icon="eternal_starlight:glistering_greatsword",
  size=1.3,
  desc=[
      ('The dagger of hunger devours foes, the bow of blood drinks life, the gravity pickaxe pulls ore itself.',
       'Кинжал голода жрёт врагов, кровавый лук пьёт жизнь, гравитационная кирка тянет руду сама.'),
      ('Every unique weapon has its own temper - try all twenty-seven.',
       'У каждого уникального оружия свой характер — проверь все двадцать семь.'),
  ],
  tasks=[
      item("eternal_starlight:dagger_of_hunger"),
      item("eternal_starlight:shattered_sword"),
      item("eternal_starlight:shattered_sword_blade"),
      item("eternal_starlight:glistering_sword"),
      item("eternal_starlight:glistering_greatsword"),
      item("eternal_starlight:glistering_bow"),
      item("eternal_starlight:glistering_morning_star"),
      item("eternal_starlight:energy_sword"),
      item("eternal_starlight:energy_boomerang"),
      item("eternal_starlight:golem_steel_greatsword"),
      item("eternal_starlight:mechanical_crossbow"),
      item("eternal_starlight:crystal_greatsword"),
      item("eternal_starlight:crystal_crossbow"),
      item("eternal_starlight:wilted_crossbow"),
      item("eternal_starlight:moonring_bow"),
  ],
  rewards=[
  ]),

Q("q19p2", ('Unique Arms · II', 'Уникальное оружие · II'), section="arsenal",
  deps=['q19p1'],
  icon="eternal_starlight:glistering_greatsword",
  size=1.3,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:moonring_greatsword"),
      item("eternal_starlight:crescent_spear"),
      item("eternal_starlight:gravity_pickaxe"),
      item("eternal_starlight:bow_of_blood"),
      item("eternal_starlight:coldsnap"),
      item("eternal_starlight:candlash"),
      item("eternal_starlight:underminer"),
      item("eternal_starlight:flesh_grinder"),
      item("eternal_starlight:bonemore"),
      item("eternal_starlight:living_arm"),
      item("eternal_starlight:pungency_fruit_spear"),
      item("eternal_starlight:pungency_fruit_axe"),
  ],
  rewards=[
      lvl(6),
      toast('Каждое лезвие Звездосветья побывало в твоих руках.'),
  ]),

Q("q20", ('Arrows and a Quiver', 'Стрелы и колчан'), section="arsenal",
  icon="eternal_starlight:galactic_quiver",
  desc=[
      ('Seven arrow kinds: from glacite to voracious. The galactic quiver holds them all.',
       'Семь видов стрел: от леднитовых до прожорливых. Галактический колчан хранит их все.'),
      ('The aethersent arrow glows in flight - handy in a night that never ends.',
       'Эфиросцентная стрела светится в полёте — удобно ночью, которой здесь всегда.'),
  ],
  tasks=[
      item("eternal_starlight:aethersent_arrow", 4),
      item("eternal_starlight:glacite_arrow", 4),
      item("eternal_starlight:malarite_arrow", 4),
      item("eternal_starlight:amaramber_arrow", 4),
      item("eternal_starlight:thioquartz_arrow", 4),
      item("eternal_starlight:air_sac_arrow", 4),
      item("eternal_starlight:voracious_arrow", 4),
      item("eternal_starlight:galactic_quiver"),
  ],
  rewards=[
      xpr(120),
  ]),

Q("q21", ('The Raiment', 'Облачение'), section="arsenal",
  icon="eternal_starlight:aethersent_hood",
  desc=[
      ('The aethersent cape, the alchemist robe, air sac boots and four trim patterns.',
       'Эфиросцентный плащ-накидка, одеяние алхимика, ботинки из воздушного мешка и четыре узора отделки.'),
      ('Air boots soften the fall: the Abyss becomes a little kinder.',
       'Воздушные ботинки гасят падение: Бездна станет чуть добрее.'),
  ],
  tasks=[
      item("eternal_starlight:aethersent_hood"),
      item("eternal_starlight:aethersent_cape"),
      item("eternal_starlight:aethersent_bottoms"),
      item("eternal_starlight:aethersent_boots"),
      item("eternal_starlight:alchemist_mask"),
      item("eternal_starlight:alchemist_robe"),
      item("eternal_starlight:air_sac_boots"),
      item("eternal_starlight:keeper_armor_trim_smithing_template"),
      item("eternal_starlight:forge_armor_trim_smithing_template"),
      item("eternal_starlight:blooming_armor_trim_smithing_template"),
      item("eternal_starlight:twining_armor_trim_smithing_template"),
  ],
  rewards=[
      xpr(140),
  ]),

# --- секция table ---
Q("q22p1", ('The Star Kitchen · I', 'Звёздная кухня · I'), section="table",
  deps=['q21'],
  icon="eternal_starlight:bouldershroom_stew",
  size=1.2,
  desc=[
      ('Everything edible in the Starlight on one table: from lunar berries to bouldershroom stew.',
       'Всё съедобное Звездосветья на одном столе: от лунных ягод до тушёных валуногрибов.'),
      ('Spicy millet gives numbness - it absorbs damage. Bouldershroom stew lets you climb cliffs.',
       'Острое просо даёт эффект онемения — он поглощает урон. Тушёные валуногрибы дают лазать по скалам.'),
  ],
  tasks=[
      item("eternal_starlight:abyssal_fruit"),
      item("eternal_starlight:aureate_flower"),
      item("eternal_starlight:aurora_deer_steak"),
      item("eternal_starlight:bouldershroom_stew"),
      item("eternal_starlight:carved_lunaris_cactus_fruit"),
      item("eternal_starlight:cooked_aurora_deer_steak"),
      item("eternal_starlight:cooked_luminaris"),
      item("eternal_starlight:cooked_luminofish"),
      item("eternal_starlight:cooked_ratlin_meat"),
      item("eternal_starlight:cooked_rookfish"),
      item("eternal_starlight:cooked_shadow_snail_meat"),
      item("eternal_starlight:crinoa"),
      item("eternal_starlight:crinoa_porridge"),
      item("eternal_starlight:forgotten_nocturnal_millet"),
      item("eternal_starlight:gleech_egg"),
  ],
  rewards=[
  ]),

Q("q22p2", ('The Star Kitchen · II', 'Звёздная кухня · II'), section="table",
  deps=['q22p1'],
  icon="eternal_starlight:bouldershroom_stew",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:jinglestem_crisp"),
      item("eternal_starlight:jinglestem_sandwich"),
      item("eternal_starlight:lunar_berries"),
      item("eternal_starlight:lunaris_cactus_fruit"),
      item("eternal_starlight:lunaris_cactus_fruit_lantern"),
      item("eternal_starlight:lunaris_cactus_gel"),
      item("eternal_starlight:lunaris_cactus_gel_block"),
      item("eternal_starlight:nocturnal_millet"),
      item("eternal_starlight:pungency_fruit"),
      item("eternal_starlight:pungency_fruit_axe"),
      item("eternal_starlight:pungency_fruit_seeds"),
      item("eternal_starlight:pungency_fruit_spear"),
      item("eternal_starlight:pungency_fruit_spear_inventory"),
      item("eternal_starlight:pungency_fruit_spear_throwing"),
      item("eternal_starlight:pungency_fruit_upgrade_smithing_template"),
  ],
  rewards=[
  ]),

Q("q22p3", ('The Star Kitchen · III', 'Звёздная кухня · III'), section="table",
  deps=['q22p2'],
  icon="eternal_starlight:bouldershroom_stew",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:pungency_stew"),
      item("eternal_starlight:ratlin_meat"),
      item("eternal_starlight:roasted_forgotten_nocturnal_millet"),
      item("eternal_starlight:rookfish_skewer"),
      item("eternal_starlight:rotten_flesh_jerky"),
      item("eternal_starlight:rotten_ham"),
      item("eternal_starlight:shadow_escargot"),
      item("eternal_starlight:shadow_snail_meat"),
      item("eternal_starlight:shadow_snail_pie"),
      item("eternal_starlight:shivering_gel"),
      item("eternal_starlight:silver_pungency_fruit"),
      item("eternal_starlight:solar_egg"),
      item("eternal_starlight:starfire_bird_egg"),
      item("eternal_starlight:starfire_hammer"),
      item("eternal_starlight:starfire_hammer_inventory"),
  ],
  rewards=[
  ]),

Q("q22p4", ('The Star Kitchen · IV', 'Звёздная кухня · IV'), section="table",
  deps=['q22p3'],
  icon="eternal_starlight:bouldershroom_stew",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:thermal_springstone_hammer"),
      item("eternal_starlight:thermal_springstone_hammer_inventory"),
  ],
  rewards=[
      xpr(200),
      toast('Звёздная кухня: всё съедобное попробовано.'),
  ]),

Q("q23p1", ('Amulets and Curios · I', 'Амулеты и диковины · I'), section="table",
  icon="eternal_starlight:butterfly_wings_amulet",
  desc=[
      ('Pocket miracles: amulets, pendants, bombs and the orb of prophecy once more - now as a trophy.',
       'Карманные чудеса: амулеты, подвески, бомбы и сфера пророчества ещё раз — теперь как трофей.'),
      ('The aetherstrike rocket calls a meteor shower. Make a wish.',
       'Эфирная ударная ракета вызывает метеоритный дождь. Загадай желание.'),
  ],
  tasks=[
      item("eternal_starlight:butterfly_wings_amulet"),
      item("eternal_starlight:fungus_amulet"),
      item("eternal_starlight:crescent_pendant"),
      item("eternal_starlight:battleaxe_pendant"),
      item("eternal_starlight:warhammer_pendant"),
      item("eternal_starlight:orb_of_prophecy"),
      item("eternal_starlight:chain_of_souls"),
      item("eternal_starlight:soulit_spectator"),
      item("eternal_starlight:book"),
      item("eternal_starlight:starlit_painting"),
      item("eternal_starlight:starlight_silver_coin"),
      item("eternal_starlight:sonar_bomb"),
      item("eternal_starlight:tear_bomb"),
      item("eternal_starlight:frozen_bomb"),
      item("eternal_starlight:frozen_tube"),
  ],
  rewards=[
  ]),

Q("q23p2", ('Amulets and Curios · II', 'Амулеты и диковины · II'), section="table",
  deps=['q23p1'],
  icon="eternal_starlight:butterfly_wings_amulet",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:ashen_snowball"),
      item("eternal_starlight:aetherstrike_rocket"),
      item("eternal_starlight:saltpeter_matchbox"),
      item("eternal_starlight:seeking_eye"),
      item("eternal_starlight:blossom_of_stars"),
      item("eternal_starlight:tenacious_vine"),
      item("eternal_starlight:shadow_snail_shell"),
      item("eternal_starlight:shadow_snail_shell_powder"),
  ],
  rewards=[
      xpr(160),
  ]),

Q("q24p1", ('Music of the Spheres · I', 'Музыка сфер · I'), section="table",
  icon="eternal_starlight:music_disc_solaris",
  desc=[
      ('24 discs are hidden in structure chests and boss pockets.',
       '24 пластинки спрятаны в сундуках структур и карманах боссов.'),
      ('A jukebox in your overworld home is the best way to remember the stars.',
       'Проигрыватель в земном доме — лучший способ вспомнить звёзды.'),
  ],
  tasks=[
      item("eternal_starlight:music_disc_brisk"),
      item("eternal_starlight:music_disc_deep_blue"),
      item("eternal_starlight:music_disc_dusk_o_ereyesterday"),
      item("eternal_starlight:music_disc_ether_rain"),
      item("eternal_starlight:music_disc_fake_light"),
      item("eternal_starlight:music_disc_les_iles_du_ciel"),
      item("eternal_starlight:music_disc_mechanical_fossil"),
      item("eternal_starlight:music_disc_moonlight"),
      item("eternal_starlight:music_disc_nest"),
      item("eternal_starlight:music_disc_nest_ii"),
      item("eternal_starlight:music_disc_optimized_option"),
      item("eternal_starlight:music_disc_posterity"),
      item("eternal_starlight:music_disc_profundity"),
      item("eternal_starlight:music_disc_sacred_desert"),
      item("eternal_starlight:music_disc_solaris"),
  ],
  rewards=[
  ]),

Q("q24p2", ('Music of the Spheres · II', 'Музыка сфер · II'), section="table",
  deps=['q24p1'],
  icon="eternal_starlight:music_disc_solaris",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:music_disc_spirit"),
      item("eternal_starlight:music_disc_stars_shining_upon_the_sea"),
      item("eternal_starlight:music_disc_the_dark_side"),
      item("eternal_starlight:music_disc_the_thorny_reign"),
      item("eternal_starlight:music_disc_tranquility"),
      item("eternal_starlight:music_disc_tranquility_ii"),
      item("eternal_starlight:music_disc_viridescent"),
      item("eternal_starlight:music_disc_wailing_well"),
      item("eternal_starlight:music_disc_whisper_of_the_stars"),
  ],
  rewards=[
      xpr(180),
  ]),

# --- секция building ---
Q("q25p1", ('Lunar and Northland · I', 'Лунный и северный · I'), section="building",
  deps=['q24p2'],
  icon="eternal_starlight:lunar_planks",
  desc=[
      ('Full building sets of the first two woods: from log to sign.',
       'Полные строительные наборы двух первых пород: от бревна до таблички.'),
      ('Northland wood smells of pine and snow - check with your nose.',
       'Северное дерево пахнет хвоей и снегом — проверь носом.'),
  ],
  tasks=[
      item("eternal_starlight:lunar_log"),
      item("eternal_starlight:lunar_wood"),
      item("eternal_starlight:lunar_planks"),
      item("eternal_starlight:lunar_leaves"),
      item("eternal_starlight:lunar_sapling"),
      item("eternal_starlight:lunar_door"),
      item("eternal_starlight:lunar_trapdoor"),
      item("eternal_starlight:lunar_slab"),
      item("eternal_starlight:lunar_stairs"),
      item("eternal_starlight:lunar_fence"),
      item("eternal_starlight:lunar_fence_gate"),
      item("eternal_starlight:lunar_button"),
      item("eternal_starlight:lunar_pressure_plate"),
      item("eternal_starlight:lunar_sign"),
      item("eternal_starlight:lunar_hanging_sign"),
  ],
  rewards=[
  ]),

Q("q25p2", ('Lunar and Northland · II', 'Лунный и северный · II'), section="building",
  deps=['q25p1'],
  icon="eternal_starlight:lunar_planks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:northland_log"),
      item("eternal_starlight:northland_wood"),
      item("eternal_starlight:northland_planks"),
      item("eternal_starlight:northland_leaves"),
      item("eternal_starlight:northland_sapling"),
      item("eternal_starlight:northland_door"),
      item("eternal_starlight:northland_trapdoor"),
      item("eternal_starlight:northland_slab"),
      item("eternal_starlight:northland_stairs"),
      item("eternal_starlight:northland_fence"),
      item("eternal_starlight:northland_fence_gate"),
      item("eternal_starlight:northland_button"),
      item("eternal_starlight:northland_pressure_plate"),
      item("eternal_starlight:northland_sign"),
      item("eternal_starlight:northland_hanging_sign"),
  ],
  rewards=[
      xpr(150),
  ]),

Q("q26p1", ('Banyin and Scarlet · I', 'Баньян и алый · I'), section="building",
  icon="eternal_starlight:scarlet_planks",
  desc=[
      ('Banyin bends, scarlet burns with colour: both beg into an interior.',
       'Баньян гнётся, алый лес горит цветом: оба просятся в интерьер.'),
      ('Scarlet leaves fold into piles - a soft floor for a greenhouse.',
       'Алые листья складываются в кучки — мягкий пол для оранжереи.'),
  ],
  tasks=[
      item("eternal_starlight:banyin_log"),
      item("eternal_starlight:banyin_wood"),
      item("eternal_starlight:banyin_planks"),
      item("eternal_starlight:banyin_leaves"),
      item("eternal_starlight:banyin_sapling"),
      item("eternal_starlight:banyin_door"),
      item("eternal_starlight:banyin_trapdoor"),
      item("eternal_starlight:banyin_slab"),
      item("eternal_starlight:banyin_stairs"),
      item("eternal_starlight:banyin_fence"),
      item("eternal_starlight:banyin_fence_gate"),
      item("eternal_starlight:banyin_button"),
      item("eternal_starlight:banyin_pressure_plate"),
      item("eternal_starlight:banyin_sign"),
      item("eternal_starlight:banyin_hanging_sign"),
  ],
  rewards=[
  ]),

Q("q26p2", ('Banyin and Scarlet · II', 'Баньян и алый · II'), section="building",
  deps=['q26p1'],
  icon="eternal_starlight:scarlet_planks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:scarlet_log"),
      item("eternal_starlight:scarlet_wood"),
      item("eternal_starlight:scarlet_planks"),
      item("eternal_starlight:scarlet_leaves"),
      item("eternal_starlight:scarlet_sapling"),
      item("eternal_starlight:scarlet_door"),
      item("eternal_starlight:scarlet_trapdoor"),
      item("eternal_starlight:scarlet_slab"),
      item("eternal_starlight:scarlet_stairs"),
      item("eternal_starlight:scarlet_fence"),
      item("eternal_starlight:scarlet_fence_gate"),
      item("eternal_starlight:scarlet_button"),
      item("eternal_starlight:scarlet_pressure_plate"),
      item("eternal_starlight:scarlet_sign"),
      item("eternal_starlight:scarlet_hanging_sign"),
  ],
  rewards=[
      xpr(150),
  ]),

Q("q27p1", ('Torreya, Jinglestem, Cradlewood · I', 'Тис, звоноствол, колыбельник · I'), section="building",
  icon="eternal_starlight:torreya_planks",
  desc=[
      ('Three late woods plus torreya tiles, campfire and vines.',
       'Три поздние породы плюс тисовый плитняк, костёр и лоза.'),
      ('Jinglestem rings in the wind: a raft of it is music on the road.',
       'Звоноствол звенит на ветру: плот из него — и музыка в дороге.'),
  ],
  tasks=[
      item("eternal_starlight:torreya_log"),
      item("eternal_starlight:torreya_wood"),
      item("eternal_starlight:torreya_planks"),
      item("eternal_starlight:torreya_leaves"),
      item("eternal_starlight:torreya_sapling"),
      item("eternal_starlight:torreya_door"),
      item("eternal_starlight:torreya_trapdoor"),
      item("eternal_starlight:torreya_slab"),
      item("eternal_starlight:torreya_stairs"),
      item("eternal_starlight:torreya_fence"),
      item("eternal_starlight:torreya_fence_gate"),
      item("eternal_starlight:torreya_button"),
      item("eternal_starlight:torreya_pressure_plate"),
      item("eternal_starlight:torreya_sign"),
      item("eternal_starlight:torreya_hanging_sign"),
  ],
  rewards=[
  ]),

Q("q27p2", ('Torreya, Jinglestem, Cradlewood · II', 'Тис, звоноствол, колыбельник · II'), section="building",
  deps=['q27p1'],
  icon="eternal_starlight:torreya_planks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:jinglestem_log"),
      item("eternal_starlight:jinglestem_wood"),
      item("eternal_starlight:jinglestem_planks"),
      item("eternal_starlight:jinglestem_sapling"),
      item("eternal_starlight:jinglestem_door"),
      item("eternal_starlight:jinglestem_trapdoor"),
      item("eternal_starlight:jinglestem_slab"),
      item("eternal_starlight:jinglestem_stairs"),
      item("eternal_starlight:jinglestem_fence"),
      item("eternal_starlight:jinglestem_fence_gate"),
      item("eternal_starlight:jinglestem_button"),
      item("eternal_starlight:jinglestem_pressure_plate"),
      item("eternal_starlight:jinglestem_sign"),
      item("eternal_starlight:jinglestem_hanging_sign"),
      item("eternal_starlight:cradlewood_log"),
  ],
  rewards=[
  ]),

Q("q27p3", ('Torreya, Jinglestem, Cradlewood · III', 'Тис, звоноствол, колыбельник · III'), section="building",
  deps=['q27p2'],
  icon="eternal_starlight:torreya_planks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:cradlewood_wood"),
      item("eternal_starlight:cradlewood_planks"),
      item("eternal_starlight:cradlewood_leaves"),
      item("eternal_starlight:cradlewood_sapling"),
      item("eternal_starlight:cradlewood_door"),
      item("eternal_starlight:cradlewood_trapdoor"),
      item("eternal_starlight:cradlewood_slab"),
      item("eternal_starlight:cradlewood_stairs"),
      item("eternal_starlight:cradlewood_fence"),
      item("eternal_starlight:cradlewood_fence_gate"),
      item("eternal_starlight:cradlewood_button"),
      item("eternal_starlight:cradlewood_pressure_plate"),
      item("eternal_starlight:cradlewood_sign"),
      item("eternal_starlight:cradlewood_hanging_sign"),
      item("eternal_starlight:torreya_tiles"),
  ],
  rewards=[
  ]),

Q("q27p4", ('Torreya, Jinglestem, Cradlewood · IV', 'Тис, звоноствол, колыбельник · IV'), section="building",
  deps=['q27p3'],
  icon="eternal_starlight:torreya_planks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:torreya_campfire"),
      item("eternal_starlight:torreya_vines"),
  ],
  rewards=[
      xpr(170),
  ]),

Q("q28p1", ('Мракокамень и бездносланец · I', 'Мракокамень и бездносланец · I'), section="building",
  icon="eternal_starlight:grimstone_bricks",
  desc=[
      ('The building family "Мракокамень и бездносланец": every slab, stair and wall of the set.',
       'Строительное семейство «мракокамень и бездносланец»: все плиты, ступени и стены набора.'),
      ('A full set = not a single block of the family is lost.',
       'Полный набор = ни один блок семейства не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:abysslate"),
      item("eternal_starlight:cobbled_grimstone"),
      item("eternal_starlight:cobbled_grimstone_slab"),
      item("eternal_starlight:cobbled_grimstone_stairs"),
      item("eternal_starlight:cobbled_grimstone_wall"),
      item("eternal_starlight:cryobysslate"),
      item("eternal_starlight:grimstone"),
      item("eternal_starlight:grimstone_brick_slab"),
      item("eternal_starlight:grimstone_brick_stairs"),
      item("eternal_starlight:grimstone_brick_wall"),
      item("eternal_starlight:grimstone_bricks"),
      item("eternal_starlight:grimstone_deepsilver_ore"),
      item("eternal_starlight:grimstone_golem_spawn_egg"),
      item("eternal_starlight:grimstone_malarite_ore"),
      item("eternal_starlight:grimstone_redstone_ore"),
  ],
  rewards=[
  ]),

Q("q28p2", ('Мракокамень и бездносланец · II', 'Мракокамень и бездносланец · II'), section="building",
  deps=['q28p1'],
  icon="eternal_starlight:grimstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:grimstone_saltpeter_ore"),
      item("eternal_starlight:grimstone_slab"),
      item("eternal_starlight:grimstone_stairs"),
      item("eternal_starlight:grimstone_starcore_ore"),
      item("eternal_starlight:grimstone_starlit_diamond_ore"),
      item("eternal_starlight:grimstone_tile_slab"),
      item("eternal_starlight:grimstone_tile_stairs"),
      item("eternal_starlight:grimstone_tile_wall"),
      item("eternal_starlight:grimstone_tiles"),
      item("eternal_starlight:grimstone_wall"),
      item("eternal_starlight:polished_abysslate"),
      item("eternal_starlight:polished_abysslate_brick_slab"),
      item("eternal_starlight:polished_abysslate_brick_stairs"),
      item("eternal_starlight:polished_abysslate_brick_wall"),
      item("eternal_starlight:polished_abysslate_bricks"),
  ],
  rewards=[
  ]),

Q("q28p3", ('Мракокамень и бездносланец · III', 'Мракокамень и бездносланец · III'), section="building",
  deps=['q28p2'],
  icon="eternal_starlight:grimstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:polished_abysslate_slab"),
      item("eternal_starlight:polished_abysslate_stairs"),
      item("eternal_starlight:polished_abysslate_wall"),
      item("eternal_starlight:polished_cryobysslate"),
      item("eternal_starlight:polished_cryobysslate_brick_slab"),
      item("eternal_starlight:polished_cryobysslate_brick_stairs"),
      item("eternal_starlight:polished_cryobysslate_brick_wall"),
      item("eternal_starlight:polished_cryobysslate_bricks"),
      item("eternal_starlight:polished_cryobysslate_slab"),
      item("eternal_starlight:polished_cryobysslate_stairs"),
      item("eternal_starlight:polished_cryobysslate_wall"),
      item("eternal_starlight:polished_grimstone"),
      item("eternal_starlight:polished_grimstone_slab"),
      item("eternal_starlight:polished_grimstone_stairs"),
      item("eternal_starlight:polished_grimstone_tile_slab"),
  ],
  rewards=[
  ]),

Q("q28p4", ('Мракокамень и бездносланец · IV', 'Мракокамень и бездносланец · IV'), section="building",
  deps=['q28p3'],
  icon="eternal_starlight:grimstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:polished_grimstone_tile_stairs"),
      item("eternal_starlight:polished_grimstone_tile_wall"),
      item("eternal_starlight:polished_grimstone_tiles"),
      item("eternal_starlight:polished_grimstone_wall"),
      item("eternal_starlight:polished_thermabysslate"),
      item("eternal_starlight:polished_thermabysslate_brick_slab"),
      item("eternal_starlight:polished_thermabysslate_brick_stairs"),
      item("eternal_starlight:polished_thermabysslate_brick_wall"),
      item("eternal_starlight:polished_thermabysslate_bricks"),
      item("eternal_starlight:polished_thermabysslate_slab"),
      item("eternal_starlight:polished_thermabysslate_stairs"),
      item("eternal_starlight:polished_thermabysslate_wall"),
      item("eternal_starlight:thermabysslate"),
  ],
  rewards=[
      xpr(170),
  ]),

Q("q29p1", ('Пустокамень, радианит и прочие · I', 'Пустокамень, радианит и прочие · I'), section="building",
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('The building family "Пустокамень, радианит и прочие": every slab, stair and wall of the set.',
       'Строительное семейство «пустокамень, радианит и прочие»: все плиты, ступени и стены набора.'),
      ('A full set = not a single block of the family is lost.',
       'Полный набор = ни один блок семейства не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:amaramber_brick_slab"),
      item("eternal_starlight:amaramber_brick_stairs"),
      item("eternal_starlight:amaramber_brick_wall"),
      item("eternal_starlight:cobbled_radianite"),
      item("eternal_starlight:cobbled_radianite_slab"),
      item("eternal_starlight:cobbled_radianite_stairs"),
      item("eternal_starlight:cobbled_radianite_wall"),
      item("eternal_starlight:cobbled_voidstone"),
      item("eternal_starlight:cobbled_voidstone_slab"),
      item("eternal_starlight:cobbled_voidstone_stairs"),
      item("eternal_starlight:cobbled_voidstone_wall"),
      item("eternal_starlight:cut_flare_brick_slab"),
      item("eternal_starlight:cut_flare_brick_stairs"),
      item("eternal_starlight:cut_flare_brick_wall"),
      item("eternal_starlight:cut_flare_tile_slab"),
  ],
  rewards=[
  ]),

Q("q29p2", ('Пустокамень, радианит и прочие · II', 'Пустокамень, радианит и прочие · II'), section="building",
  deps=['q29p1'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:cut_flare_tile_stairs"),
      item("eternal_starlight:cut_flare_tile_wall"),
      item("eternal_starlight:doomeden_brick_slab"),
      item("eternal_starlight:doomeden_brick_stairs"),
      item("eternal_starlight:doomeden_brick_wall"),
      item("eternal_starlight:doomeden_tile_slab"),
      item("eternal_starlight:doomeden_tile_stairs"),
      item("eternal_starlight:doomeden_tile_wall"),
      item("eternal_starlight:dusted_brick_slab"),
      item("eternal_starlight:dusted_brick_stairs"),
      item("eternal_starlight:dusted_brick_wall"),
      item("eternal_starlight:eternal_ice_brick_slab"),
      item("eternal_starlight:eternal_ice_brick_stairs"),
      item("eternal_starlight:eternal_ice_brick_wall"),
      item("eternal_starlight:flare_brick"),
  ],
  rewards=[
  ]),

Q("q29p3", ('Пустокамень, радианит и прочие · III', 'Пустокамень, радианит и прочие · III'), section="building",
  deps=['q29p2'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:flare_brick_slab"),
      item("eternal_starlight:flare_brick_stairs"),
      item("eternal_starlight:flare_brick_wall"),
      item("eternal_starlight:flare_tile_slab"),
      item("eternal_starlight:flare_tile_stairs"),
      item("eternal_starlight:flare_tile_wall"),
      item("eternal_starlight:haze_ice_brick_slab"),
      item("eternal_starlight:haze_ice_brick_stairs"),
      item("eternal_starlight:haze_ice_brick_wall"),
      item("eternal_starlight:lunar_mosaic"),
      item("eternal_starlight:lunar_mosaic_fence"),
      item("eternal_starlight:lunar_mosaic_fence_gate"),
      item("eternal_starlight:lunar_mosaic_slab"),
      item("eternal_starlight:lunar_mosaic_stairs"),
      item("eternal_starlight:molten_stellagmite"),
  ],
  rewards=[
  ]),

Q("q29p4", ('Пустокамень, радианит и прочие · IV', 'Пустокамень, радианит и прочие · IV'), section="building",
  deps=['q29p3'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:molten_stellagmite_slab"),
      item("eternal_starlight:molten_stellagmite_stairs"),
      item("eternal_starlight:molten_stellagmite_wall"),
      item("eternal_starlight:nebulaite_brick_slab"),
      item("eternal_starlight:nebulaite_brick_stairs"),
      item("eternal_starlight:nebulaite_brick_wall"),
      item("eternal_starlight:nightfall_mud_brick_slab"),
      item("eternal_starlight:nightfall_mud_brick_stairs"),
      item("eternal_starlight:nightfall_mud_brick_wall"),
      item("eternal_starlight:polished_doomeden_brick_slab"),
      item("eternal_starlight:polished_doomeden_brick_stairs"),
      item("eternal_starlight:polished_doomeden_brick_wall"),
      item("eternal_starlight:polished_radianite"),
      item("eternal_starlight:polished_radianite_slab"),
      item("eternal_starlight:polished_radianite_stairs"),
  ],
  rewards=[
  ]),

Q("q29p5", ('Пустокамень, радианит и прочие · V', 'Пустокамень, радианит и прочие · V'), section="building",
  deps=['q29p4'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:polished_radianite_wall"),
      item("eternal_starlight:polished_springstone"),
      item("eternal_starlight:polished_springstone_slab"),
      item("eternal_starlight:polished_springstone_stairs"),
      item("eternal_starlight:polished_springstone_wall"),
      item("eternal_starlight:polished_stellagmite"),
      item("eternal_starlight:polished_stellagmite_slab"),
      item("eternal_starlight:polished_stellagmite_stairs"),
      item("eternal_starlight:polished_stellagmite_wall"),
      item("eternal_starlight:polished_toxite"),
      item("eternal_starlight:polished_toxite_slab"),
      item("eternal_starlight:polished_toxite_stairs"),
      item("eternal_starlight:polished_toxite_wall"),
      item("eternal_starlight:polished_voidstone"),
      item("eternal_starlight:polished_voidstone_slab"),
  ],
  rewards=[
  ]),

Q("q29p6", ('Пустокамень, радианит и прочие · VI', 'Пустокамень, радианит и прочие · VI'), section="building",
  deps=['q29p5'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:polished_voidstone_stairs"),
      item("eternal_starlight:polished_voidstone_wall"),
      item("eternal_starlight:radianite"),
      item("eternal_starlight:radianite_brick_slab"),
      item("eternal_starlight:radianite_brick_stairs"),
      item("eternal_starlight:radianite_brick_wall"),
      item("eternal_starlight:radianite_bricks"),
      item("eternal_starlight:radianite_pillar"),
      item("eternal_starlight:radianite_slab"),
      item("eternal_starlight:radianite_stairs"),
      item("eternal_starlight:radianite_wall"),
      item("eternal_starlight:springstone"),
      item("eternal_starlight:springstone_brick_slab"),
      item("eternal_starlight:springstone_brick_stairs"),
      item("eternal_starlight:springstone_brick_wall"),
  ],
  rewards=[
  ]),

Q("q29p7", ('Пустокамень, радианит и прочие · VII', 'Пустокамень, радианит и прочие · VII'), section="building",
  deps=['q29p6'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:springstone_bricks"),
      item("eternal_starlight:springstone_slab"),
      item("eternal_starlight:springstone_stairs"),
      item("eternal_starlight:springstone_wall"),
      item("eternal_starlight:stellagmite"),
      item("eternal_starlight:stellagmite_slab"),
      item("eternal_starlight:stellagmite_stairs"),
      item("eternal_starlight:stellagmite_wall"),
      item("eternal_starlight:thermal_springstone"),
      item("eternal_starlight:thermal_springstone_axe"),
      item("eternal_starlight:thermal_springstone_boots"),
      item("eternal_starlight:thermal_springstone_brick_slab"),
      item("eternal_starlight:thermal_springstone_brick_stairs"),
      item("eternal_starlight:thermal_springstone_brick_wall"),
      item("eternal_starlight:thermal_springstone_bricks"),
  ],
  rewards=[
  ]),

Q("q29p8", ('Пустокамень, радианит и прочие · VIII', 'Пустокамень, радианит и прочие · VIII'), section="building",
  deps=['q29p7'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:thermal_springstone_chestplate"),
      item("eternal_starlight:thermal_springstone_hammer"),
      item("eternal_starlight:thermal_springstone_hammer_inventory"),
      item("eternal_starlight:thermal_springstone_helmet"),
      item("eternal_starlight:thermal_springstone_hoe"),
      item("eternal_starlight:thermal_springstone_ingot"),
      item("eternal_starlight:thermal_springstone_leggings"),
      item("eternal_starlight:thermal_springstone_pickaxe"),
      item("eternal_starlight:thermal_springstone_scythe"),
      item("eternal_starlight:thermal_springstone_scythe_inventory"),
      item("eternal_starlight:thermal_springstone_shovel"),
      item("eternal_starlight:thermal_springstone_slab"),
      item("eternal_starlight:thermal_springstone_stairs"),
      item("eternal_starlight:thermal_springstone_sword"),
      item("eternal_starlight:thermal_springstone_wall"),
  ],
  rewards=[
  ]),

Q("q29p9", ('Пустокамень, радианит и прочие · IX', 'Пустокамень, радианит и прочие · IX'), section="building",
  deps=['q29p8'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:tooth_of_hunger_tile_slab"),
      item("eternal_starlight:tooth_of_hunger_tile_stairs"),
      item("eternal_starlight:tooth_of_hunger_tile_wall"),
      item("eternal_starlight:toxite"),
      item("eternal_starlight:toxite_brick_slab"),
      item("eternal_starlight:toxite_brick_stairs"),
      item("eternal_starlight:toxite_brick_wall"),
      item("eternal_starlight:toxite_bricks"),
      item("eternal_starlight:toxite_slab"),
      item("eternal_starlight:toxite_stairs"),
      item("eternal_starlight:toxite_wall"),
      item("eternal_starlight:voidstone"),
      item("eternal_starlight:voidstone_brick_slab"),
      item("eternal_starlight:voidstone_brick_stairs"),
      item("eternal_starlight:voidstone_brick_wall"),
  ],
  rewards=[
  ]),

Q("q29p10", ('Пустокамень, радианит и прочие · X', 'Пустокамень, радианит и прочие · X'), section="building",
  deps=['q29p9'],
  icon="eternal_starlight:voidstone_bricks",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:voidstone_bricks"),
      item("eternal_starlight:voidstone_deepsilver_ore"),
      item("eternal_starlight:voidstone_malarite_ore"),
      item("eternal_starlight:voidstone_redstone_ore"),
      item("eternal_starlight:voidstone_saltpeter_ore"),
      item("eternal_starlight:voidstone_slab"),
      item("eternal_starlight:voidstone_spike"),
      item("eternal_starlight:voidstone_stairs"),
      item("eternal_starlight:voidstone_starcore_ore"),
      item("eternal_starlight:voidstone_starlit_diamond_ore"),
      item("eternal_starlight:voidstone_tile_slab"),
      item("eternal_starlight:voidstone_tile_stairs"),
      item("eternal_starlight:voidstone_tile_wall"),
      item("eternal_starlight:voidstone_tiles"),
      item("eternal_starlight:voidstone_wall"),
  ],
  rewards=[
      xpr(170),
  ]),

Q("q30p1", ('Light and Crystals · I', 'Свет и кристаллы · I'), section="building",
  icon="eternal_starlight:red_starlight_crystal_lantern",
  desc=[
      ('Every light source and crystal of the dimension: clusters, lanterns, reinforced ice and star cores.',
       'Все источники света и кристаллы измерения: друы, фонари, усиленный лёд и звёздные ядра.'),
      ('Light here is not decor: in the Starlight dark it keeps your sanity.',
       'Свет здесь — не декор: в темноте Звездосветья он держит рассудок.'),
  ],
  tasks=[
      item("eternal_starlight:amaramber_candle"),
      item("eternal_starlight:amaramber_lantern"),
      item("eternal_starlight:blooming_blue_starlight_crystal_cluster"),
      item("eternal_starlight:blooming_red_starlight_crystal_cluster"),
      item("eternal_starlight:blue_starlight_crystal_block"),
      item("eternal_starlight:blue_starlight_crystal_cluster"),
      item("eternal_starlight:blue_starlight_crystal_lantern"),
      item("eternal_starlight:doomed_redstone_torch"),
      item("eternal_starlight:doomed_torch"),
      item("eternal_starlight:doomeden_light"),
      item("eternal_starlight:dusk_light"),
      item("eternal_starlight:eternal_ice"),
      item("eternal_starlight:eternal_ice_lantern"),
      item("eternal_starlight:haze_ice_lantern"),
      item("eternal_starlight:lunaris_cactus_fruit_lantern"),
  ],
  rewards=[
  ]),

Q("q30p2", ('Light and Crystals · II', 'Свет и кристаллы · II'), section="building",
  deps=['q30p1'],
  icon="eternal_starlight:red_starlight_crystal_lantern",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:music_disc_fake_light"),
      item("eternal_starlight:orbflora_light"),
      item("eternal_starlight:red_starlight_crystal_block"),
      item("eternal_starlight:red_starlight_crystal_cluster"),
      item("eternal_starlight:red_starlight_crystal_lantern"),
      item("eternal_starlight:reinforced_dusk_light"),
      item("eternal_starlight:reinforced_ice"),
      item("eternal_starlight:reinforced_ice_pane"),
      item("eternal_starlight:starcore_light"),
      item("eternal_starlight:thin_eternal_ice"),
  ],
  rewards=[
      xpr(150),
  ]),

Q("q31p1", ('Flora and Fauna in Blocks · I', 'Флора и фауна в блоках · I'), section="building",
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Flowers, grasses, mushrooms, corals, yeti furs and starfire bird aviaries - everything that grows or lives as a block.',
       'Цветы, травы, грибы, кораллы, меха йети и вольеры птиц-звездопалов — всё, что растёт и живёт блоком.'),
      ('An aviary with seeds inside breeds the birds: that is how starfire is got.',
       'Вольер с семенами внутри размножает птиц: так добывают звездопал.'),
  ],
  tasks=[
      item("eternal_starlight:acacia_starfire_bird_aviary"),
      item("eternal_starlight:amaramber_grass"),
      item("eternal_starlight:amaramber_grass_bush"),
      item("eternal_starlight:amethysia_grass"),
      item("eternal_starlight:aureate_flower"),
      item("eternal_starlight:bamboo_starfire_bird_aviary"),
      item("eternal_starlight:banyin_starfire_bird_aviary"),
      item("eternal_starlight:birch_starfire_bird_aviary"),
      item("eternal_starlight:black_yeti_fur"),
      item("eternal_starlight:black_yeti_fur_carpet"),
      item("eternal_starlight:blazebank_grass"),
      item("eternal_starlight:blue_crystal_moss_block"),
      item("eternal_starlight:blue_crystal_moss_carpet"),
      item("eternal_starlight:blue_yeti_fur"),
      item("eternal_starlight:blue_yeti_fur_carpet"),
  ],
  rewards=[
  ]),

Q("q31p2", ('Flora and Fauna in Blocks · II', 'Флора и фауна в блоках · II'), section="building",
  deps=['q31p1'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:bouldershroom"),
      item("eternal_starlight:brown_yeti_fur"),
      item("eternal_starlight:brown_yeti_fur_carpet"),
      item("eternal_starlight:cave_moss"),
      item("eternal_starlight:cave_moss_block"),
      item("eternal_starlight:cave_moss_carpet"),
      item("eternal_starlight:cherry_starfire_bird_aviary"),
      item("eternal_starlight:conebloom"),
      item("eternal_starlight:cradlewood_starfire_bird_aviary"),
      item("eternal_starlight:crescent_grass"),
      item("eternal_starlight:crimson_starfire_bird_aviary"),
      item("eternal_starlight:crystallized_lunar_grass"),
      item("eternal_starlight:crystallized_sand"),
      item("eternal_starlight:crystallum_coral"),
      item("eternal_starlight:cyan_yeti_fur"),
  ],
  rewards=[
  ]),

Q("q31p3", ('Flora and Fauna in Blocks · III', 'Флора и фауна в блоках · III'), section="building",
  deps=['q31p2'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:cyan_yeti_fur_carpet"),
      item("eternal_starlight:dark_oak_starfire_bird_aviary"),
      item("eternal_starlight:dead_crystallum_coral"),
      item("eternal_starlight:dead_golden_coral"),
      item("eternal_starlight:dead_lunar_bush"),
      item("eternal_starlight:dead_tentacles_coral"),
      item("eternal_starlight:dusted_gravel"),
      item("eternal_starlight:fantasy_grass_block"),
      item("eternal_starlight:fantasy_grass_carpet"),
      item("eternal_starlight:gleech_egg"),
      item("eternal_starlight:glimmerfly_bush"),
      item("eternal_starlight:glowing_crescent_grass"),
      item("eternal_starlight:glowing_lunar_bush"),
      item("eternal_starlight:glowing_lunar_grass"),
      item("eternal_starlight:glowing_mossy_dusted_gravel"),
  ],
  rewards=[
  ]),

Q("q31p4", ('Flora and Fauna in Blocks · IV', 'Флора и фауна в блоках · IV'), section="building",
  deps=['q31p3'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:glowing_mushroom"),
      item("eternal_starlight:glowing_night_sprouts"),
      item("eternal_starlight:glowing_nightfall_mud"),
      item("eternal_starlight:glowing_parasol_grass"),
      item("eternal_starlight:golden_coral"),
      item("eternal_starlight:golden_grass"),
      item("eternal_starlight:golden_grass_block"),
      item("eternal_starlight:gray_yeti_fur"),
      item("eternal_starlight:gray_yeti_fur_carpet"),
      item("eternal_starlight:green_yeti_fur"),
      item("eternal_starlight:green_yeti_fur_carpet"),
      item("eternal_starlight:jinglestem_starfire_bird_aviary"),
      item("eternal_starlight:jungle_starfire_bird_aviary"),
      item("eternal_starlight:light_blue_yeti_fur"),
      item("eternal_starlight:light_blue_yeti_fur_carpet"),
  ],
  rewards=[
  ]),

Q("q31p5", ('Flora and Fauna in Blocks · V', 'Флора и фауна в блоках · V'), section="building",
  deps=['q31p4'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:light_gray_yeti_fur"),
      item("eternal_starlight:light_gray_yeti_fur_carpet"),
      item("eternal_starlight:lime_yeti_fur"),
      item("eternal_starlight:lime_yeti_fur_carpet"),
      item("eternal_starlight:lunar_bush"),
      item("eternal_starlight:lunar_grass"),
      item("eternal_starlight:lunar_starfire_bird_aviary"),
      item("eternal_starlight:magenta_yeti_fur"),
      item("eternal_starlight:magenta_yeti_fur_carpet"),
      item("eternal_starlight:mangrove_starfire_bird_aviary"),
      item("eternal_starlight:moonlight_bush"),
      item("eternal_starlight:moonlight_lily_pad"),
      item("eternal_starlight:mossy_dusted_gravel"),
      item("eternal_starlight:night_sprouts"),
      item("eternal_starlight:nightfall_dirt"),
  ],
  rewards=[
  ]),

Q("q31p6", ('Flora and Fauna in Blocks · VI', 'Флора и фауна в блоках · VI'), section="building",
  deps=['q31p5'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:nightfall_grass_block"),
      item("eternal_starlight:nightfall_mud"),
      item("eternal_starlight:nightfan_bush"),
      item("eternal_starlight:northland_starfire_bird_aviary"),
      item("eternal_starlight:oak_starfire_bird_aviary"),
      item("eternal_starlight:orange_yeti_fur"),
      item("eternal_starlight:orange_yeti_fur_carpet"),
      item("eternal_starlight:packed_nightfall_mud"),
      item("eternal_starlight:parasol_grass"),
      item("eternal_starlight:pink_rose"),
      item("eternal_starlight:pink_rose_bush"),
      item("eternal_starlight:pink_yeti_fur"),
      item("eternal_starlight:pink_yeti_fur_carpet"),
      item("eternal_starlight:purple_yeti_fur"),
      item("eternal_starlight:purple_yeti_fur_carpet"),
  ],
  rewards=[
  ]),

Q("q31p7", ('Flora and Fauna in Blocks · VII', 'Флора и фауна в блоках · VII'), section="building",
  deps=['q31p6'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:red_crystal_moss_block"),
      item("eternal_starlight:red_crystal_moss_carpet"),
      item("eternal_starlight:red_velvetumoss_flower"),
      item("eternal_starlight:red_yeti_fur"),
      item("eternal_starlight:red_yeti_fur_carpet"),
      item("eternal_starlight:sacred_starlight_flower"),
      item("eternal_starlight:scarlet_grass"),
      item("eternal_starlight:scarlet_starfire_bird_aviary"),
      item("eternal_starlight:shining_mushroom"),
      item("eternal_starlight:small_glowing_night_sprouts"),
      item("eternal_starlight:small_night_sprouts"),
      item("eternal_starlight:solar_egg"),
      item("eternal_starlight:spiral_kelp"),
      item("eternal_starlight:spruce_starfire_bird_aviary"),
      item("eternal_starlight:starfire_bird_egg"),
  ],
  rewards=[
  ]),

Q("q31p8", ('Flora and Fauna in Blocks · VIII', 'Флора и фауна в блоках · VIII'), section="building",
  deps=['q31p7'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:starfire_bird_nest"),
      item("eternal_starlight:starlight_flower"),
      item("eternal_starlight:starlight_seagrass"),
      item("eternal_starlight:starlight_torchflower"),
      item("eternal_starlight:starlit_lily_pad"),
      item("eternal_starlight:stellafly_bush"),
      item("eternal_starlight:sunset_thornbloom"),
      item("eternal_starlight:suspicious_dusted_gravel"),
      item("eternal_starlight:swamp_rose"),
      item("eternal_starlight:tall_crescent_grass"),
      item("eternal_starlight:tall_glowing_crescent_grass"),
      item("eternal_starlight:tall_golden_grass"),
      item("eternal_starlight:tenacious_nightfall_grass_block"),
      item("eternal_starlight:tentacles_coral"),
      item("eternal_starlight:torreya_starfire_bird_aviary"),
  ],
  rewards=[
  ]),

Q("q31p9", ('Flora and Fauna in Blocks · IX', 'Флора и фауна в блоках · IX'), section="building",
  deps=['q31p8'],
  icon="eternal_starlight:pink_rose",
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:torreya_vines"),
      item("eternal_starlight:twilight_sand"),
      item("eternal_starlight:warped_starfire_bird_aviary"),
      item("eternal_starlight:whisperbloom"),
      item("eternal_starlight:white_yeti_fur"),
      item("eternal_starlight:white_yeti_fur_carpet"),
      item("eternal_starlight:wick_grass"),
      item("eternal_starlight:withered_starlight_flower"),
      item("eternal_starlight:yellow_yeti_fur"),
      item("eternal_starlight:yellow_yeti_fur_carpet"),
  ],
  rewards=[
      xpr(170),
  ]),

Q("q32p1", ('Ores, Mechanisms, Storage · I', 'Руды, механизмы, хранение · I'), section="building",
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Every ore vein, furnace, grate, pillar and storage block of the dimension - down to the last.',
       'Все рудные жилы, печи, решётки, колонны и складские блоки измерения — до последнего.'),
      ('Suspicious dimslag is brushed clean: ancient tears inside.',
       'Подозрительный тусклошлак чистится кистью: внутри древние слёзы.'),
  ],
  tasks=[
      item("eternal_starlight:abyssal_geyser"),
      item("eternal_starlight:abyssal_magma_block"),
      item("eternal_starlight:aethersent_block"),
      item("eternal_starlight:amaramber_bricks"),
      item("eternal_starlight:blazing_starcore_block"),
      item("eternal_starlight:bouldershroom_block"),
      item("eternal_starlight:charged_chiseled_polished_doomeden_bricks"),
      item("eternal_starlight:chiseled_flare_pillar"),
      item("eternal_starlight:chiseled_golem_steel_block"),
      item("eternal_starlight:chiseled_grimstone"),
      item("eternal_starlight:chiseled_nebulaite_bricks"),
      item("eternal_starlight:chiseled_polished_abysslate"),
      item("eternal_starlight:chiseled_polished_cryobysslate"),
      item("eternal_starlight:chiseled_polished_doomeden_bricks"),
      item("eternal_starlight:chiseled_polished_thermabysslate"),
  ],
  rewards=[
  ]),

Q("q32p2", ('Ores, Mechanisms, Storage · II', 'Руды, механизмы, хранение · II'), section="building",
  deps=['q32p1'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:chiseled_radianite"),
      item("eternal_starlight:chiseled_springstone"),
      item("eternal_starlight:chiseled_tooth_of_hunger_tiles"),
      item("eternal_starlight:chiseled_toxite"),
      item("eternal_starlight:chiseled_twilight_sandstone"),
      item("eternal_starlight:chiseled_voidstone"),
      item("eternal_starlight:cracked_grimstone_bricks"),
      item("eternal_starlight:cracked_grimstone_tiles"),
      item("eternal_starlight:cracked_voidstone_bricks"),
      item("eternal_starlight:cracked_voidstone_tiles"),
      item("eternal_starlight:cryobyssal_geyser"),
      item("eternal_starlight:cryobyssal_magma_block"),
      item("eternal_starlight:crystallum_coral_block"),
      item("eternal_starlight:cut_flare_bricks"),
      item("eternal_starlight:cut_flare_tiles"),
  ],
  rewards=[
  ]),

Q("q32p3", ('Ores, Mechanisms, Storage · III', 'Руды, механизмы, хранение · III'), section="building",
  deps=['q32p2'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:dead_crystallum_coral_block"),
      item("eternal_starlight:dead_golden_coral_block"),
      item("eternal_starlight:dead_tentacles_coral_block"),
      item("eternal_starlight:deepsilver_bars"),
      item("eternal_starlight:deepsilver_block"),
      item("eternal_starlight:deepsilver_grate"),
      item("eternal_starlight:doomeden_bricks"),
      item("eternal_starlight:doomeden_keyhole"),
      item("eternal_starlight:doomeden_tiles"),
      item("eternal_starlight:dusted_bricks"),
      item("eternal_starlight:eclipse_core"),
      item("eternal_starlight:energy_block"),
      item("eternal_starlight:eternal_ice_bricks"),
      item("eternal_starlight:eternal_ice_deepsilver_ore"),
      item("eternal_starlight:eternal_ice_redstone_ore"),
  ],
  rewards=[
  ]),

Q("q32p4", ('Ores, Mechanisms, Storage · IV', 'Руды, механизмы, хранение · IV'), section="building",
  deps=['q32p3'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:eternal_ice_saltpeter_ore"),
      item("eternal_starlight:eternal_ice_starcore_ore"),
      item("eternal_starlight:eternal_ice_starlit_diamond_ore"),
      item("eternal_starlight:flare_bricks"),
      item("eternal_starlight:flare_spawner"),
      item("eternal_starlight:flare_tiles"),
      item("eternal_starlight:flowglaze_bricks"),
      item("eternal_starlight:flowglaze_pane"),
      item("eternal_starlight:glacite_block"),
      item("eternal_starlight:gloreed"),
      item("eternal_starlight:glowing_mushroom_block"),
      item("eternal_starlight:golden_coral_block"),
      item("eternal_starlight:golem_steel_bars"),
      item("eternal_starlight:golem_steel_block"),
      item("eternal_starlight:golem_steel_crate"),
  ],
  rewards=[
  ]),

Q("q32p5", ('Ores, Mechanisms, Storage · V', 'Руды, механизмы, хранение · V'), section="building",
  deps=['q32p4'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:golem_steel_grate"),
      item("eternal_starlight:golem_steel_jet"),
      item("eternal_starlight:golem_steel_pillar"),
      item("eternal_starlight:golem_steel_tiles"),
      item("eternal_starlight:haze_ice_bricks"),
      item("eternal_starlight:haze_ice_deepsilver_ore"),
      item("eternal_starlight:haze_ice_redstone_ore"),
      item("eternal_starlight:haze_ice_saltpeter_ore"),
      item("eternal_starlight:haze_ice_starcore_ore"),
      item("eternal_starlight:haze_ice_starlit_diamond_ore"),
      item("eternal_starlight:lunar_monstrosity_spawner"),
      item("eternal_starlight:malarite_block"),
      item("eternal_starlight:marimold_block"),
      item("eternal_starlight:mechanical_spawner"),
      item("eternal_starlight:nebulaite_bricks"),
  ],
  rewards=[
  ]),

Q("q32p6", ('Ores, Mechanisms, Storage · VI', 'Руды, механизмы, хранение · VI'), section="building",
  deps=['q32p5'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:nightfall_mud_bricks"),
      item("eternal_starlight:nightfall_mud_deepsilver_ore"),
      item("eternal_starlight:nightfall_mud_malarite_ore"),
      item("eternal_starlight:oxidized_alloy_furnace"),
      item("eternal_starlight:oxidized_chiseled_golem_steel_block"),
      item("eternal_starlight:oxidized_golem_steel_bars"),
      item("eternal_starlight:oxidized_golem_steel_block"),
      item("eternal_starlight:oxidized_golem_steel_grate"),
      item("eternal_starlight:oxidized_golem_steel_jet"),
      item("eternal_starlight:oxidized_golem_steel_pillar"),
      item("eternal_starlight:oxidized_golem_steel_tiles"),
      item("eternal_starlight:packed_nightfall_mud_deepsilver_ore"),
      item("eternal_starlight:packed_nightfall_mud_malarite_ore"),
      item("eternal_starlight:permafrost_spawner"),
      item("eternal_starlight:polished_doomeden_bricks"),
  ],
  rewards=[
  ]),

Q("q32p7", ('Ores, Mechanisms, Storage · VII', 'Руды, механизмы, хранение · VII'), section="building",
  deps=['q32p6'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:raw_aethersent_block"),
      item("eternal_starlight:raw_amaramber_block"),
      item("eternal_starlight:raw_deepsilver_block"),
      item("eternal_starlight:raw_flowglaze"),
      item("eternal_starlight:redstone_doomeden_keyhole"),
      item("eternal_starlight:saltpeter_block"),
      item("eternal_starlight:shining_mushroom_block"),
      item("eternal_starlight:starcore_block"),
      item("eternal_starlight:starlight_golem_spawner"),
      item("eternal_starlight:starlit_diamond_block"),
      item("eternal_starlight:suspicious_dimslag"),
      item("eternal_starlight:tentacles_coral_block"),
      item("eternal_starlight:the_gatekeeper_spawner"),
      item("eternal_starlight:thermabyssal_geyser"),
      item("eternal_starlight:thermabyssal_magma_block"),
  ],
  rewards=[
  ]),

Q("q32p8", ('Ores, Mechanisms, Storage · VIII', 'Руды, механизмы, хранение · VIII'), section="building",
  deps=['q32p7'],
  icon="eternal_starlight:voidstone_starlit_diamond_ore",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:thioquartz_block"),
      item("eternal_starlight:tooth_of_hunger_tiles"),
      item("eternal_starlight:unrealium_bars"),
      item("eternal_starlight:unrealium_block"),
      item("eternal_starlight:waxed_alloy_furnace"),
      item("eternal_starlight:waxed_chiseled_golem_steel_block"),
      item("eternal_starlight:waxed_golem_steel_bars"),
      item("eternal_starlight:waxed_golem_steel_block"),
      item("eternal_starlight:waxed_golem_steel_grate"),
      item("eternal_starlight:waxed_golem_steel_jet"),
      item("eternal_starlight:waxed_golem_steel_pillar"),
      item("eternal_starlight:waxed_golem_steel_tiles"),
  ],
  rewards=[
      xpr(200),
  ]),

Q("q33p1", ('And Every Other Block · I', 'И каждый прочий блок · I'), section="building",
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Everything that did not fit the themes above: not a single block of the mod is lost.',
       'Всё, что не вошло в темы выше: ни один блок мода не потерян.'),
      ('Finish this quest - and you hold the whole Starlight building yard in your hand.',
       'Собрал этот квест — держи в руке весь строительный склад Звездосветья.'),
  ],
  tasks=[
      item("eternal_starlight:accumulator"),
      item("eternal_starlight:algaleaves"),
      item("eternal_starlight:ashen_snow"),
      item("eternal_starlight:banyin_roots"),
      item("eternal_starlight:blooming_shadegrieve"),
      item("eternal_starlight:blue_crystal_roots"),
      item("eternal_starlight:blue_crystalfleur"),
      item("eternal_starlight:blue_crystalfleur_vine"),
      item("eternal_starlight:blue_crystallized_lunar_log"),
      item("eternal_starlight:bouldershroom_roots"),
      item("eternal_starlight:bouldershroom_stem"),
      item("eternal_starlight:budding_thioquartz"),
      item("eternal_starlight:circulush"),
      item("eternal_starlight:crescentleaf"),
      item("eternal_starlight:crinoa_bale"),
  ],
  rewards=[
  ]),

Q("q33p2", ('And Every Other Block · II', 'И каждый прочий блок · II'), section="building",
  deps=['q33p1'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:crystallum_coral_fan"),
      item("eternal_starlight:cut_twilight_sandstone"),
      item("eternal_starlight:cut_twilight_sandstone_slab"),
      item("eternal_starlight:cut_twilight_sandstone_stairs"),
      item("eternal_starlight:cut_twilight_sandstone_wall"),
      item("eternal_starlight:cyan_lunar_leaves"),
      item("eternal_starlight:dead_crystallum_coral_fan"),
      item("eternal_starlight:dead_golden_coral_fan"),
      item("eternal_starlight:dead_lunar_log"),
      item("eternal_starlight:dead_tentacles_coral_fan"),
      item("eternal_starlight:desert_amethysia"),
      item("eternal_starlight:dimslag"),
      item("eternal_starlight:drying_rack"),
      item("eternal_starlight:dusk_emitter"),
      item("eternal_starlight:dusk_glass"),
  ],
  rewards=[
  ]),

Q("q33p3", ('And Every Other Block · III', 'И каждый прочий блок · III'), section="building",
  deps=['q33p2'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:dusk_lockbox"),
      item("eternal_starlight:energy_transmitter"),
      item("eternal_starlight:fantabud"),
      item("eternal_starlight:fantafern"),
      item("eternal_starlight:fantagrass"),
      item("eternal_starlight:fire_orchid"),
      item("eternal_starlight:flowglaze_brick_slab"),
      item("eternal_starlight:flowglaze_brick_stairs"),
      item("eternal_starlight:flowglaze_brick_wall"),
      item("eternal_starlight:glacite"),
      item("eternal_starlight:gladespike"),
      item("eternal_starlight:glintgrass"),
      item("eternal_starlight:gloomcandle_root"),
      item("eternal_starlight:glowing_grimstone"),
      item("eternal_starlight:glowing_mushroom_stem"),
  ],
  rewards=[
  ]),

Q("q33p4", ('And Every Other Block · IV', 'И каждый прочий блок · IV'), section="building",
  deps=['q33p3'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:glowing_voidstone"),
      item("eternal_starlight:glowlis"),
      item("eternal_starlight:golden_coral_fan"),
      item("eternal_starlight:golem_steel_slab"),
      item("eternal_starlight:golem_steel_stairs"),
      item("eternal_starlight:golem_steel_tile_slab"),
      item("eternal_starlight:golem_steel_tile_stairs"),
      item("eternal_starlight:green_fantabud"),
      item("eternal_starlight:green_fantafern"),
      item("eternal_starlight:green_fantagrass"),
      item("eternal_starlight:hanging_algaleaves"),
      item("eternal_starlight:hanging_fantagrass"),
      item("eternal_starlight:haze_ice"),
      item("eternal_starlight:icicle"),
      item("eternal_starlight:jingling_pickle"),
  ],
  rewards=[
  ]),

Q("q33p5", ('And Every Other Block · V', 'И каждый прочий блок · V'), section="building",
  deps=['q33p4'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:loot_chest"),
      item("eternal_starlight:lumenstem"),
      item("eternal_starlight:luminis"),
      item("eternal_starlight:lunar_mat"),
      item("eternal_starlight:lunar_reed"),
      item("eternal_starlight:lunar_vine"),
      item("eternal_starlight:lunaris_cactus"),
      item("eternal_starlight:marimold"),
      item("eternal_starlight:marimold_stem"),
      item("eternal_starlight:mauve_fern"),
      item("eternal_starlight:moonlight_duckweed"),
      item("eternal_starlight:muddy_banyin_roots"),
      item("eternal_starlight:nebulaite"),
      item("eternal_starlight:nightfall_dirt_path"),
      item("eternal_starlight:nightfall_farmland"),
  ],
  rewards=[
  ]),

Q("q33p6", ('And Every Other Block · VI', 'И каждый прочий блок · VI'), section="building",
  deps=['q33p5'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:nightfall_podzol"),
      item("eternal_starlight:nightfan"),
      item("eternal_starlight:orange_scarlet_bud"),
      item("eternal_starlight:orbflora"),
      item("eternal_starlight:oxidized_golem_steel_slab"),
      item("eternal_starlight:oxidized_golem_steel_stairs"),
      item("eternal_starlight:oxidized_golem_steel_tile_slab"),
      item("eternal_starlight:oxidized_golem_steel_tile_stairs"),
      item("eternal_starlight:purple_lunar_leaves"),
      item("eternal_starlight:purple_scarlet_bud"),
      item("eternal_starlight:red_crystal_roots"),
      item("eternal_starlight:red_crystalfleur"),
      item("eternal_starlight:red_crystalfleur_vine"),
      item("eternal_starlight:red_crystallized_lunar_log"),
      item("eternal_starlight:red_scarlet_bud"),
  ],
  rewards=[
  ]),

Q("q33p7", ('And Every Other Block · VII', 'И каждый прочий блок · VII'), section="building",
  deps=['q33p6'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:red_velvetumoss"),
      item("eternal_starlight:red_velvetumoss_villi"),
      item("eternal_starlight:sacred_lanternvine"),
      item("eternal_starlight:scarlet_leaves_pile"),
      item("eternal_starlight:sea_rosa"),
      item("eternal_starlight:shadegrieve"),
      item("eternal_starlight:shining_mushroom_stem"),
      item("eternal_starlight:stonett"),
      item("eternal_starlight:stripped_banyin_log"),
      item("eternal_starlight:stripped_banyin_wood"),
      item("eternal_starlight:stripped_cradlewood_log"),
      item("eternal_starlight:stripped_cradlewood_wood"),
      item("eternal_starlight:stripped_jinglestem_log"),
      item("eternal_starlight:stripped_jinglestem_wood"),
      item("eternal_starlight:stripped_lunar_log"),
  ],
  rewards=[
  ]),

Q("q33p8", ('And Every Other Block · VIII', 'И каждый прочий блок · VIII'), section="building",
  deps=['q33p7'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:stripped_lunar_wood"),
      item("eternal_starlight:stripped_northland_log"),
      item("eternal_starlight:stripped_northland_wood"),
      item("eternal_starlight:stripped_scarlet_log"),
      item("eternal_starlight:stripped_scarlet_wood"),
      item("eternal_starlight:stripped_torreya_log"),
      item("eternal_starlight:stripped_torreya_wood"),
      item("eternal_starlight:tall_gladespike"),
      item("eternal_starlight:tangled_skull"),
      item("eternal_starlight:tentacles_coral_fan"),
      item("eternal_starlight:thioquartz_cluster"),
      item("eternal_starlight:torreya_tile_slab"),
      item("eternal_starlight:torreya_tile_stairs"),
      item("eternal_starlight:torreya_tile_wall"),
      item("eternal_starlight:twilight_sandstone"),
  ],
  rewards=[
  ]),

Q("q33p9", ('And Every Other Block · IX', 'И каждый прочий блок · IX'), section="building",
  deps=['q33p8'],
  icon="eternal_starlight:starlit_diamond_block",
  size=1.2,
  desc=[
      ('Continuation of the set: not a single block or item of the theme is lost.',
       'Продолжение набора: ни один блок и ни один предмет темы не потеряны.'),
  ],
  tasks=[
      item("eternal_starlight:twilight_sandstone_slab"),
      item("eternal_starlight:twilight_sandstone_stairs"),
      item("eternal_starlight:twilight_sandstone_wall"),
      item("eternal_starlight:twilvewyrm_herb"),
      item("eternal_starlight:velvetumoss"),
      item("eternal_starlight:velvetumoss_villi"),
      item("eternal_starlight:vividstalk"),
      item("eternal_starlight:waxed_golem_steel_slab"),
      item("eternal_starlight:waxed_golem_steel_stairs"),
      item("eternal_starlight:waxed_golem_steel_tile_slab"),
      item("eternal_starlight:waxed_golem_steel_tile_stairs"),
      item("eternal_starlight:withered_desert_amethysia"),
  ],
  rewards=[
      xpr(200),
  ]),

# --- секция encyc ---
Q("q34p1", ('The Star Encyclopaedia · I', 'Звёздная энциклопедия · I'), section="encyc",
  deps=['q06', 'q12', 'q14', 'q21', 'q24p2', 'q33p9'],
  icon="eternal_starlight:blossom_of_stars",
  size=1.8,
  desc=[
      ('The final frontier: everything not covered by the sections above - every item of the mod is accounted for here.',
       'Финальный рубеж: всё, что не вошло в разделы выше, — каждый предмет мода учтён здесь.'),
      ('Hand in the encyclopaedia - and the chapter closes without a single blank in the content list.',
       'Сдай энциклопедию — и глава закроется без единой белой полосы в списке контента.'),
  ],
  tasks=[
      item("eternal_starlight:aethersent_nugget"),
      item("eternal_starlight:air_sac_mask"),
      item("eternal_starlight:amaramber_axe"),
      item("eternal_starlight:amaramber_hoe"),
      item("eternal_starlight:amaramber_ingot"),
      item("eternal_starlight:amaramber_mask"),
      item("eternal_starlight:amaramber_nugget"),
      item("eternal_starlight:amaramber_pickaxe"),
      item("eternal_starlight:amaramber_shovel"),
      item("eternal_starlight:amaramber_sickle"),
      item("eternal_starlight:aurora_deer_antler"),
      item("eternal_starlight:blue_starlight_crystal_shard"),
      item("eternal_starlight:broken_doomeden_bone"),
      item("eternal_starlight:cinder_brick"),
      item("eternal_starlight:creteor_hide"),
  ],
  rewards=[
  ]),

Q("q34p2", ('The Star Encyclopaedia · II', 'Звёздная энциклопедия · II'), section="encyc",
  deps=['q34p1'],
  icon="eternal_starlight:blossom_of_stars",
  size=1.8,
  desc=[
      ('Volume II of the encyclopaedia: every item of the mod is accounted for, not one is lost.',
       'Том II энциклопедии: учтён каждый предмет мода, ни один не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:crinoa_seeds"),
      item("eternal_starlight:deepsilver_hoe"),
      item("eternal_starlight:deepsilver_nugget"),
      item("eternal_starlight:deepsilver_shovel"),
      item("eternal_starlight:doomeden_carrion"),
      item("eternal_starlight:doomeden_rag"),
      item("eternal_starlight:doomeden_rapier"),
      item("eternal_starlight:ether_bucket"),
      item("eternal_starlight:etheric_eye"),
      item("eternal_starlight:eye_of_doom"),
      item("eternal_starlight:flowglaze_hoe"),
      item("eternal_starlight:flowglaze_shovel"),
      item("eternal_starlight:glacite_hoe"),
      item("eternal_starlight:glacite_shovel"),
      item("eternal_starlight:golem_steel_nugget"),
  ],
  rewards=[
  ]),

Q("q34p3", ('The Star Encyclopaedia · III', 'Звёздная энциклопедия · III'), section="encyc",
  deps=['q34p2'],
  icon="eternal_starlight:blossom_of_stars",
  size=1.8,
  desc=[
      ('Volume III of the encyclopaedia: every item of the mod is accounted for, not one is lost.',
       'Том III энциклопедии: учтён каждый предмет мода, ни один не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:loot_bag"),
      item("eternal_starlight:luminaris"),
      item("eternal_starlight:luminaris_bucket"),
      item("eternal_starlight:luminofish"),
      item("eternal_starlight:luminofish_bucket"),
      item("eternal_starlight:malarite_hoe"),
      item("eternal_starlight:malarite_shovel"),
      item("eternal_starlight:nightfall_spider_eye"),
      item("eternal_starlight:nocturnal_millet_seeds"),
      item("eternal_starlight:oxidized_golem_steel_ingot"),
      item("eternal_starlight:oxidized_golem_steel_nugget"),
      item("eternal_starlight:pearl_necklace"),
      item("eternal_starlight:petal_scythe"),
      item("eternal_starlight:popped_nocturnal_millet_bucket"),
      item("eternal_starlight:rage_of_stars"),
  ],
  rewards=[
  ]),

Q("q34p4", ('The Star Encyclopaedia · IV', 'Звёздная энциклопедия · IV'), section="encyc",
  deps=['q34p3'],
  icon="eternal_starlight:blossom_of_stars",
  size=1.8,
  desc=[
      ('Volume IV of the encyclopaedia: every item of the mod is accounted for, not one is lost.',
       'Том IV энциклопедии: учтён каждый предмет мода, ни один не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:raw_aethersent"),
      item("eternal_starlight:raw_deepsilver"),
      item("eternal_starlight:red_starlight_crystal_shard"),
      item("eternal_starlight:rookfish"),
      item("eternal_starlight:rookfish_air_sac"),
      item("eternal_starlight:rookfish_bucket"),
      item("eternal_starlight:seeds_launcher"),
      item("eternal_starlight:seeker_tentacle"),
      item("eternal_starlight:starfall_longbow"),
      item("eternal_starlight:starfire_hoe"),
      item("eternal_starlight:starfire_shovel"),
      item("eternal_starlight:starlit_diamond_hoe"),
      item("eternal_starlight:starlit_diamond_shovel"),
      item("eternal_starlight:tear_bomb_minecart"),
      item("eternal_starlight:tenacious_petal"),
  ],
  rewards=[
  ]),

Q("q34p5", ('The Star Encyclopaedia · V', 'Звёздная энциклопедия · V'), section="encyc",
  deps=['q34p4'],
  icon="eternal_starlight:blossom_of_stars",
  size=1.8,
  desc=[
      ('Volume V of the encyclopaedia: every item of the mod is accounted for, not one is lost.',
       'Том V энциклопедии: учтён каждый предмет мода, ни один не потерян.'),
  ],
  tasks=[
      item("eternal_starlight:tentacle_spike"),
      item("eternal_starlight:tooth_of_hunger"),
      item("eternal_starlight:unrealium_hoe"),
      item("eternal_starlight:unrealium_nugget"),
      item("eternal_starlight:unrealium_shovel"),
      item("eternal_starlight:wand_of_teleportation"),
  ],
  rewards=[
      lvl(30),
      give(CUSTOM["premium"]),
      toast('Вечное Звездосветье познано полностью. Ни один предмет не потерян.'),
  ]),

]

CHAPTER = {
    "id": 0xC005, "filename": "starlight",
    "layout": "blocks", "cols": 2, "dx": 2.1, "dy": 1.45,
    "pad_x": 4.5, "pad_y": 6.5,
    "shape": "hexagon", "icon": "eternal_starlight:orb_of_prophecy",
    "banner": "banner_starlight", "banner_w": 13.0, "banner_h": 3.25,
    "banner_gap": 2.9,
    "title": ("The Eternal Starlight", "Вечное Звездосветье"),
    "subtitle": [
        ("The Eternal Starlight mod: the Starlight dimension, 24 biomes, 8 "
         "structures, two bosses, nine gear tiers and over a thousand blocks "
         "and items.",
         "Мод Eternal Starlight: измерение Вечного Звездосветья, 24 биома, "
         "8 структур, два босса, девять тиров снаряжения и больше тысячи "
         "блоков и предметов."),
        ("The portal is opened by the orb of prophecy. Everything the mod "
         "has is covered here: not a single item is lost.",
         "Портал открывает сфера пророчества. Здесь раскрыто всё, что есть "
         "в моде: ни один предмет не потерян."),
    ],
    "sections": SECTIONS,
    "quests": QUESTS,
    "images": [],
    "links": [],
}
