#Настройки Iris, поставляемые паком «Вечное Звездосветье» (v1.6.1).
#Файл синхронизируется packsync в options/ игровую папки инстанса.
#Complementary Reimagined лежит в shaderpacks/ и включён сразу:
#отключается в игре: Options -> Video Settings -> Shader Packs -> Off.
shaderPack=ComplementaryReimagined_r5.9.3.zip
enableShaders=true
